CREATE TABLE [dbo].[ARTICLE] (
    [ARTICLEID]       UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[ARTICLENAME]     VARCHAR (100) ,
	[COLOURID]        UNIQUEIDENTIFIER,
	[COLORNAME]       VARCHAR (100) ,
	[COLORCODE]       VARCHAR (100) ,
	[PRODUCTID]       UNIQUEIDENTIFIER FOREIGN KEY REFERENCES PRODUCT(PRODUCTID)
);
